### ISSUE TITLE
Stock Main Menu in customisation crashes TF2 on startup

### ISSUE THREAD

**Issue by AaronionRings** [MedicodiBiscotti/biscottiHUD#2]
If you use the contents of "[MAIN MENU] stock" folder from the customisation folder to use as the main menu then TF2 will crash on loading the main menu every time. Your default, main menu for this hud works perfectly so I think it's just a case of the stock one not having been updated.

**Comment by MedicodiBiscotti** [comment]
Cheers! I've fixed it now. The reason I didn't notice this when testing the stock menu is because I launched the game with the custom one and then changed it while the game was open. It was actually only crashing if you launched the game with the stock one. Basically, it needed stuff from the custom one, and if you launched without that, it would crash.
It's fixed now, thanks mate :)
