### ISSUE TITLE
Box above players head when centering crosshair on them looks blocky, perhaps a bug? See screenshot

### ISSUE THREAD

**Issue by VandenPlause** [MedicodiBiscotti/biscottiHUD#4]
Hello, is this effect normal in game?

http://steamcommunity.com/id/VandenPlause/screenshot/853855683708491126

Look at the health box above the heavy's head.

Just want to make sure it's not just a graphical issue on my end.

Thanks for all the work on the HUD!

**Comment by MedicodiBiscotti** [comment]
It's by design. I like the HP as a square. There's a customization to turn it back into a cross, "[HP SPEC STYLE] cross".
I also play without floating health. I think that's why there's the little "appendage" to the right. It's not there with floating disabled. I could probably crank up the tall to make is as large as the rest of the block but then it would still go past the HP number and look off.
Floating HP is personal preference. It's sad that the squared HP apparently has issues with it. I don't know how to fix it if it even can be fixed.
